server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # API gateway: http://localhost:4004/auth/login
        # auth service: http://auth-service:4005/login
        - id: auth-service-route
          uri: http://host.docker.internal:4005 # using docker internal service discovery tool, docker will handle the rest
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1 # strips the first word after the first slash
            # api gateway: http://localhost:4004/api/patients
            # patient service: http://patient-service:4000/patients
            - JwtValidation # specifies that we want jwt verification: looks for AbstractGatewayFilterFactory for rules

        - id: api-doc-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
            # api gateway: http://localhost:4004/api-doc/patients
            # patient service: http://patient-service:4000/v3/api-doc

        - id: api-doc-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

